//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER ONS.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITIES.
        /// </summary>
        internal static string ACTIVITIES {
            get {
                return ResourceManager.GetString("ACTIVITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        internal static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to Be Paid.
        /// </summary>
        internal static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To.
        /// </summary>
        internal static string BackTo {
            get {
                return ResourceManager.GetString("BackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Due.
        /// </summary>
        internal static string BalanceDue {
            get {
                return ResourceManager.GetString("BalanceDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Due Date.
        /// </summary>
        internal static string BalanceDueDate {
            get {
                return ResourceManager.GetString("BalanceDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance needs to be paid in the centre on the party day..
        /// </summary>
        internal static string BalancePayment {
            get {
                return ResourceManager.GetString("BalancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Class Now.
        /// </summary>
        internal static string BookClassesNow {
            get {
                return ResourceManager.GetString("BookClassesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked At.
        /// </summary>
        internal static string BookedAt {
            get {
                return ResourceManager.GetString("BookedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked By.
        /// </summary>
        internal static string BookedBy {
            get {
                return ResourceManager.GetString("BookedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Reference.
        /// </summary>
        internal static string BookingReference {
            get {
                return ResourceManager.GetString("BookingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK NOW.
        /// </summary>
        internal static string BOOKNOW {
            get {
                return ResourceManager.GetString("BOOKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Party Now.
        /// </summary>
        internal static string BookPartyNow {
            get {
                return ResourceManager.GetString("BookPartyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Session Now.
        /// </summary>
        internal static string BookSessionNow {
            get {
                return ResourceManager.GetString("BookSessionNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged To Account.
        /// </summary>
        internal static string ChargedToAccount {
            get {
                return ResourceManager.GetString("ChargedToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        internal static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Working.
        /// </summary>
        internal static string ContinueWorking {
            get {
                return ResourceManager.GetString("ContinueWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost:.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Login.
        /// </summary>
        internal static string CustomerLogin {
            get {
                return ResourceManager.GetString("CustomerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50% Deposit : {0:c}.
        /// </summary>
        internal static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your contact details up to date.
        /// </summary>
        internal static string DetailsUpToDate {
            get {
                return ResourceManager.GetString("DetailsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount [{0}].
        /// </summary>
        internal static string DiscountNote {
            get {
                return ResourceManager.GetString("DiscountNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total &lt;b&gt;(including Promotional Code Discount)&lt;/b&gt;.
        /// </summary>
        internal static string DiscountTotal {
            get {
                return ResourceManager.GetString("DiscountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Total.
        /// </summary>
        internal static string DiscountTotal2 {
            get {
                return ResourceManager.GetString("DiscountTotal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent.
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a promotional code then please enter it in the box below.
        /// </summary>
        internal static string EnterPromo {
            get {
                return ResourceManager.GetString("EnterPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        internal static string EVENTS {
            get {
                return ResourceManager.GetString("EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        internal static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Amount : .
        /// </summary>
        internal static string FullAmount {
            get {
                return ResourceManager.GetString("FullAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiroPay.
        /// </summary>
        internal static string GiroPay {
            get {
                return ResourceManager.GetString("GiroPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Availability.
        /// </summary>
        internal static string GoodAvailability {
            get {
                return ResourceManager.GetString("GoodAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total:.
        /// </summary>
        internal static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Jump Waiver Guardian Acceptance.
        /// </summary>
        internal static string GuardianWaiverAcceptance {
            get {
                return ResourceManager.GetString("GuardianWaiverAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including.
        /// </summary>
        internal static string Including {
            get {
                return ResourceManager.GetString("Including", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;You have logged out successfully.&lt;/h2&gt;&lt;p&gt;Please use your existing username and password to access the Members area.&lt;/p&gt;.
        /// </summary>
        internal static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our booking management service. You can use the username and password you were given during booking to complete your waivers before your arrival, as well as make any further bookings..
        /// </summary>
        internal static string LoginBlurb {
            get {
                return ResourceManager.GetString("LoginBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In &lt;span&gt;Login to manage your bookings&lt;/span&gt;.
        /// </summary>
        internal static string LoginToManage {
            get {
                return ResourceManager.GetString("LoginToManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dddd dd MMMM yyyy}.
        /// </summary>
        internal static string LongDateFormat {
            get {
                return ResourceManager.GetString("LongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to manage your bookings.
        /// </summary>
        internal static string ManageBookings {
            get {
                return ResourceManager.GetString("ManageBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will only be able to jump at AirHop if you have completed our waiver. If you are under the age of 18 the waiver will need to be completed by a parent or legal guardian..
        /// </summary>
        internal static string MasterPageBox1 {
            get {
                return ResourceManager.GetString("MasterPageBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MINIMUM AGE TO BOUNCE AT AIRHOP IS 5 AND OVER.
        /// </summary>
        internal static string MasterPageBox2 {
            get {
                return ResourceManager.GetString("MasterPageBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Bristol** Please be aware that there are Height and Weight restrictions for the Wipe Out Zone. For more information, click here..
        /// </summary>
        internal static string MasterPageBox3 {
            get {
                return ResourceManager.GetString("MasterPageBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Account Balance.
        /// </summary>
        internal static string MemberAccountBalance {
            get {
                return ResourceManager.GetString("MemberAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using our mobile bookings website. If you have any issues with using the site then please let us know via the following contact methods.
        /// </summary>
        internal static string MobileMenuHelp {
            get {
                return ResourceManager.GetString("MobileMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed below are boxes where you can fill out your participants details. Please complete names, dates of birth and whether or not you are the participants parent or guardian. Once finished please click the &apos;Next&apos; button..
        /// </summary>
        internal static string MultiWaiverInfo {
            get {
                return ResourceManager.GetString("MultiWaiverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookings.
        /// </summary>
        internal static string MyBookings {
            get {
                return ResourceManager.GetString("MyBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyDetails.
        /// </summary>
        internal static string MyDetails {
            get {
                return ResourceManager.GetString("MyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate back to the.
        /// </summary>
        internal static string NavBackTo {
            get {
                return ResourceManager.GetString("NavBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need any help making your booking? Please contact us via one of the methods below..
        /// </summary>
        internal static string NeedHelpBooking {
            get {
                return ResourceManager.GetString("NeedHelpBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to pay - no payment required..
        /// </summary>
        internal static string NothingToPay {
            get {
                return ResourceManager.GetString("NothingToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Booking.
        /// </summary>
        internal static string OnlineBooking {
            get {
                return ResourceManager.GetString("OnlineBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Payment.
        /// </summary>
        internal static string OnlinePayment {
            get {
                return ResourceManager.GetString("OnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        internal static string Pair {
            get {
                return ResourceManager.GetString("Pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties.
        /// </summary>
        internal static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation doesn’t match. Please check your password..
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmation.
        /// </summary>
        internal static string PaymentConfirmation {
            get {
                return ResourceManager.GetString("PaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Successful!.
        /// </summary>
        internal static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Summary.
        /// </summary>
        internal static string PaymentSummary {
            get {
                return ResourceManager.GetString("PaymentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select --.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered.
        /// </summary>
        internal static string Powered {
            get {
                return ResourceManager.GetString("Powered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Time.
        /// </summary>
        internal static string PreferredTime {
            get {
                return ResourceManager.GetString("PreferredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid.
        /// </summary>
        internal static string Prepaid {
            get {
                return ResourceManager.GetString("Prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Payment.
        /// </summary>
        internal static string PrePayment {
            get {
                return ResourceManager.GetString("PrePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotional Code.
        /// </summary>
        internal static string Promo {
            get {
                return ResourceManager.GetString("Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Codes and Vouchers.
        /// </summary>
        internal static string PromoHeader {
            get {
                return ResourceManager.GetString("PromoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a promotional code or voucher?.
        /// </summary>
        internal static string PromoText {
            get {
                return ResourceManager.GetString("PromoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your credentials.
        /// </summary>
        internal static string ReEnter {
            get {
                return ResourceManager.GetString("ReEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * denotes required fields.
        /// </summary>
        internal static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait whilst your reservation is processed....
        /// </summary>
        internal static string ReservationProcessing {
            get {
                return ResourceManager.GetString("ReservationProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - with second hour.
        /// </summary>
        internal static string SecondHourTag {
            get {
                return ResourceManager.GetString("SecondHourTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date:.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location:.
        /// </summary>
        internal static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your preferred Payment Method.
        /// </summary>
        internal static string SelectPaymentMethod {
            get {
                return ResourceManager.GetString("SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Service.
        /// </summary>
        internal static string SelfService {
            get {
                return ResourceManager.GetString("SelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Date:.
        /// </summary>
        internal static string SessionDate {
            get {
                return ResourceManager.GetString("SessionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Time:.
        /// </summary>
        internal static string SessionTime {
            get {
                return ResourceManager.GetString("SessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign your waivers before you arrive to save time at check-in.
        /// </summary>
        internal static string SignWaivers {
            get {
                return ResourceManager.GetString("SignWaivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow your customers to complete their waivers on arrival.
        /// </summary>
        internal static string SignWaiversOnArrival {
            get {
                return ResourceManager.GetString("SignWaiversOnArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow your customers to complete their waivers and print their own wristbands.
        /// </summary>
        internal static string SignWaiversPrintWristbands {
            get {
                return ResourceManager.GetString("SignWaiversPrintWristbands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks.
        /// </summary>
        internal static string Socks {
            get {
                return ResourceManager.GetString("Socks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofort.
        /// </summary>
        internal static string Sofort {
            get {
                return ResourceManager.GetString("Sofort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Spaces.
        /// </summary>
        internal static string Spaces {
            get {
                return ResourceManager.GetString("Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may swipe across on mobile devices.
        /// </summary>
        internal static string swipeAcross {
            get {
                return ResourceManager.GetString("swipeAcross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} Team.
        /// </summary>
        internal static string TeamBlurb {
            get {
                return ResourceManager.GetString("TeamBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMSANDCONDITIONS.
        /// </summary>
        internal static string TERMSANDCONDITIONS {
            get {
                return ResourceManager.GetString("TERMSANDCONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning. Your booking session is about to expire due to inactivity..
        /// </summary>
        internal static string TimeoutWarning {
            get {
                return ResourceManager.GetString("TimeoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNS Checkout.
        /// </summary>
        internal static string TNSCheckout {
            get {
                return ResourceManager.GetString("TNSCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Pay:.
        /// </summary>
        internal static string ToPay {
            get {
                return ResourceManager.GetString("ToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost:.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        internal static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td&gt;{0} Purchased:&lt;/td&gt;&lt;td&gt;Qty: {1}, Total: {2:c} (@{3:c})&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string UpsellItemEmailFormat {
            get {
                return ResourceManager.GetString("UpsellItemEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage your upcoming bookings.
        /// </summary>
        internal static string ViewManage {
            get {
                return ResourceManager.GetString("ViewManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Code.
        /// </summary>
        internal static string VoucherCode {
            get {
                return ResourceManager.GetString("VoucherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monetary vouchers available.
        /// </summary>
        internal static string VouchersAvailable {
            get {
                return ResourceManager.GetString("VouchersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a voucher code then please enter it in the box below..
        /// </summary>
        internal static string VoucherText {
            get {
                return ResourceManager.GetString("VoucherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Details.
        /// </summary>
        internal static string WaiverDetails {
            get {
                return ResourceManager.GetString("WaiverDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you&apos;re all booked in you have the opportunity to complete your waivers now in order to save time when you arrive. This greatly reduces check-in times..
        /// </summary>
        internal static string WaiverMessage1 {
            get {
                return ResourceManager.GetString("WaiverMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have some or all of the details to hand, then please click the Participants button below, this will take you to a page where you can enter their details and complete their waivers..
        /// </summary>
        internal static string WaiverMessage2 {
            get {
                return ResourceManager.GetString("WaiverMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have the details just now, then you can always login with the credentials that we have sent in your booking email and complete them at a later time..
        /// </summary>
        internal static string WaiverMessage3 {
            get {
                return ResourceManager.GetString("WaiverMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking involves multiple reservations, so you will have fill in the participant details for each of these separately. Take a note of the booking references above, we&apos;ll take you to the first one, and then you can simply enter each of the booking references to complete the others..
        /// </summary>
        internal static string WaiverMessageMulti {
            get {
                return ResourceManager.GetString("WaiverMessageMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waivers.
        /// </summary>
        internal static string Waivers {
            get {
                return ResourceManager.GetString("Waivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiver Station.
        /// </summary>
        internal static string WaiverStation {
            get {
                return ResourceManager.GetString("WaiverStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working, please wait....
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
